:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    DocumentReminderNotifier:
      description: 'Send Notification on remind documents'
      queue: default
      cron: '0 * * * *'  # Runs every hour