:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    GenerateRoomCodeJob:
      description: 'Generate room code for consultations'
      queue: default
      cron: '*/1 * * * *'  # Runs every minute
    UpdateConsultationStatusJob:
      description: 'Update Consultation Status to finished after 12 hours of appointment date'
      queue: default
      cron: '*/1 * * * *'  # Runs every minute
    VerifyPaymentJob:
      description: 'Update Payment Status'
      queue: default
      cron: '*/1 * * * *'  # Runs every minute