- name: "Consultation dermatologique"
  description: "Examen de la peau, diagnostic et prescription de traitement."
  price: "50 - 100 TND"

- name: "Consultation spécialisée"
  description: "Analyse approfondie des problèmes dermatologiques spécifiques (acné, allergies, maladies auto-immunes, etc.)."
  price: "80 - 150 TND"

- name: "Peeling chimique"
  description: "Traitement exfoliant pour améliorer la texture de la peau et réduire les imperfections."
  price: "120 - 300 TND"

- name: "Traitement laser des taches pigmentaires"
  description: "Réduction des taches brunes et uniformisation du teint avec un laser dermatologique."
  price: "200 - 600 TND"

- name: "Injection de Botox / Acide hyaluronique"
  description: "Injections pour atténuer les rides et restaurer le volume du visage."
  price: "600 - 1 200 TND"

- name: "Ablation d’un grain de beauté"
  description: "Retrait chirurgical ou laser d’un grain de beauté suspect ou gênant."
  price: "100 - 250 TND"

- name: "Traitement des cicatrices d’acné au laser"
  description: "Laser fractionné pour améliorer l’aspect des cicatrices d’acné."
  price: "250 - 700 TND"

- name: "Épilation laser définitive"
  description: "Traitement laser pour une réduction permanente des poils sur différentes zones du corps."
  price: "150 - 800 TND (par séance)"

- name: "Cryothérapie des verrues"
  description: "Élimination des verrues par application de froid extrême."
  price: "80 - 200 TND"

- name: "Greffe de cheveux"
  description: "Implantation de follicules capillaires pour densifier les cheveux en cas de calvitie."
  price: "5 000 - 15 000 TND"

- name: "Mésothérapie capillaire"
  description: "Micro-injections de vitamines et minéraux pour stimuler la repousse des cheveux."
  price: "250 - 600 TND (par séance)"

- name: "Traitement de l'hyperpigmentation"
  description: "Utilisation de crèmes dépigmentantes, peelings ou lasers pour corriger les irrégularités de teint."
  price: "300 - 800 TND"

- name: "Traitement de la couperose et des varicosités"
  description: "Laser dermatologique pour éliminer les rougeurs et petits vaisseaux visibles."
  price: "250 - 700 TND"

- name: "Microneedling"
  description: "Stimulation du collagène par micro-aiguilles pour rajeunissement et correction des imperfections."
  price: "250 - 500 TND (par séance)"

- name: "Traitement des mycoses des ongles au laser"
  description: "Application d’un laser spécifique pour éliminer les infections fongiques des ongles."
  price: "150 - 400 TND"

- name: "Traitement de l’acné par lumière LED"
  description: "Séances de lumière bleue ou rouge pour réduire l’inflammation et l’excès de sébum."
  price: "100 - 300 TND (par séance)"

- name: "Radiofréquence pour raffermissement de la peau"
  description: "Utilisation d’ondes radio pour stimuler la production de collagène et raffermir la peau."
  price: "400 - 1 000 TND"

- name: "Plasma riche en plaquettes (PRP)"
  description: "Injection de PRP pour stimuler la régénération de la peau et la repousse des cheveux."
  price: "600 - 1 500 TND (par séance)"

- name: "Dermabrasion"
  description: "Exfoliation mécanique de la peau pour lisser le grain de peau et atténuer les cicatrices."
  price: "300 - 700 TND"

- name: "Hydrafacial"
  description: "Nettoyage en profondeur de la peau avec hydratation et extraction des impuretés."
  price: "150 - 400 TND"
